name: github-actions-test-for-ml
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - name: Model setup
      - uses: actions/setup-python@v4
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          run:
            pip install -r requirements.txt
            python train.py
     
