name: github-actions-test-for-ml
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
     steps:
      - name: cml_run
        uses: actions/checkout@v2 
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Requirements
        run:
          pip install -r requirements.txt
          python train.py
          echo "Model Metrics"
          cat metrics.txt
     
